// Generated by Wrangler by running `wrangler types --experimental-include-runtime --env-interface CloudflareEnv`

interface CloudflareEnv {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	API_URL: string;
	ENVIRONMENT: string;
	ASSETS: Fetcher;
}
