// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings env.d.ts`

interface CloudflareBindings {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	ENVIRONMENT: string;
	DOMAIN: string;
}
