name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      INFRA_DIR: 'packages/infra'
      SUPABASE_DIR: 'packages/supabase'
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup Supabase CLI
      id: setup-supabase-cli
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - run: |
        supabase link --project-ref $SUPABASE_PROJECT_ID
        supabase db push
      shell: bash
      working-directory: ${{ env.SUPABASE_DIR }}

